version: "3.9"
services:
    app:
        image: app
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "127.0.0.1:8080:8000"
        networks:
            - internal_network
        restart: on-failure
        deploy:
            resources:
                limits:
                    cpus: "1"
    db:
        image: postgres:17.0
        container_name: db
        hostname: database_host
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U &&{POSTGRES_USER} -d &&{POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
        expose:
            - "5432"
        networks:
            - internal_network
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:

networks:
    internal_network:
        driver: bridge